kind: KeycloakRealm
apiVersion: keycloak.org/v1alpha1
metadata:
  name: kafka-deep-dive-realm
  namespace: deep-dive-kafka
  labels:
    app: sso
spec:
  realm:
    id: kafka-deep-dive
    realm: kafka-deep-dive
    enabled: true
    displayName: Quarkus Deep Dive Realm
  instanceSelector:
    matchLabels:
      app: sso
