apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: deep-dive-quarkus
  labels:
    app: sso
  namespace: deep-dive-quarkus
spec:
  externalAccess:
    enabled: true
  keycloakDeploymentSpec:
    imagePullPolicy: Always
  postgresDeploymentSpec:
    imagePullPolicy: Always
  instances: 1
